### ISSUE TITLE
s3 woes...

### ISSUE THREAD

**Issue by shutteritch** [NightHawk451/testdriven-tasks#1]
I found your repo trying to solve the same problem around s3 buckets.

I tried all sorts including deleting the buckets (which isn't as straightforward as you'd hope)

What worked for me was changing the name of the bucket to be something unique:

```
custom:
  stage: ${opt:stage, self:provider.stage}
  bucketName: ${self:custom.stage}-tasks-api-ifw
  s3Sync:
    # A simple configuration for copying static assets
    - bucketName: ${self:custom.bucketName}
      localDir: dist
```
And then following the solution below ([original source](https://stackoverflow.com/questions/76097031/aws-s3-bucket-cannot-have-acls-set-with-objectownerships-bucketownerenforced-s))
```
resources:
  Resources:
    TasksAPIBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        ### No more AccessControl
        # AccessControl: PublicRead
        ###  replace it with...
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        ###
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
```
